name: Bug report
description: Report incorrect or unexpected behavior of a package
labels: [bug, need repro]
body:
  - type: dropdown
    id: package
    attributes:
      label: Which package has the bugs?
      options:
        - The core library
        - The documentation
        - WebEmbed x Shorten API
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce with below code sample:
        1. do thing
        2. do thing in Discord client
        3. observe behavior
        4. see error logs below
    validations:
      required: true
  - type: textarea
    id: codesample
    attributes:
      label: Code sample
      description: Include a reproducible, minimal code sample. This will be automatically formatted into code, so no need for backticks.
      render: typescript
      placeholder: |
        Your code sample should be...
        ... Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        ... Complete - Provide all parts someone else needs to reproduce your problem
        ... Reproducible - Test the code you're about to provide to make sure it reproduces the problem
  - type: input
    id: djs-version
    attributes:
      label: Package version
      description: Which version of are you using? Run `npm list <package>` in your project directory and paste the output.
      placeholder: Older versions are not supported.
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: |
        Which version of Node.js are you using? Run `node --version` in your project directory and paste the output.
        If you are using TypeScript, please include its version (`npm list typescript`) as well.
      placeholder: Node.js version 16.9+ is required for version 14.0.0+
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Which OS does your application run on?
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure this issue is valid!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shared the entire traceback.
          required: true
        - label: I am using a user token (and it isn't visible in the code).
          required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Put any extra context, weird configurations, or other important info here.