blank_issues_enabled: false
contact_links:
  - name: Discord.js Repo
    url: https://github.com/discordjs/discord.js
    about: A powerful JavaScript library for interacting with the Discord API [Bot].