name: Feature request
description: Request a new feature
labels: [Feature]
body:
  - type: markdown
    attributes:
      value: |
        We can only implement features that Discord publishes, documents and merges into the Discord API documentation.
        For unreleased API features, you need more documents (Unofficial Discord API) or things you know.
  - type: dropdown
    id: package
    attributes:
      label: Which package is the feature request for?
      options:
        - The core library
        - The documentation
        - WebEmbed x Shorten API
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: I'm always frustrated when..., Discord has recently released..., A good addition would be...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.